import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';

// Components
import TopNavigation from '@/components/TopNavigation';
import FooterNavigation from '@/components/FooterNavigation';
import Button from '@/components/Button';
import HeadingBBAStyle from '@/components/HeadingBBAStyle';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      <main>
        {/* Placeholder element */}
        <div className="container mx-auto">
          {/* Sample buttons */}
          <h5 className="mb-2 text-lg">
            <b>Variant &quot;primary&quot;</b> - Simple link buttons with
            default parameters.
          </h5>
          <div className="mb-5 flex items-start">
            <Button href="#" size="sm" className="mr-4">
              Learn More
            </Button>
            <Button href="#" className="mr-4">
              Learn More
            </Button>
            <Button href="#" size="lg">
              Learn More
            </Button>
          </div>

          <h5 className="mb-2 text-lg">
            <b>Variant &quot;primary-outline&quot;</b> - Buttons with outline.
          </h5>
          <div className="mb-5 flex items-start">
            <Button variant="primary-outline" size="sm" className="mr-4">
              Learn More
            </Button>
            <Button variant="primary-outline" className="mr-4">
              Learn More
            </Button>
            <Button variant="primary-outline" size="lg" className="mr-4">
              Learn More
            </Button>
          </div>

          <h5 className="mb-2 text-lg">
            <b>Variant &quot;dark&quot;</b> - Sample non-link button with custom
            padding and onClick function
          </h5>
          <div className="mb-5">
            <Button
              variant="dark"
              padding="0.5em 4em"
              onClick={() => alert('Test')}
            >
              Learn More
            </Button>
          </div>

          <h5 className="mb-2 text-lg">
            <b>Variant &quot;dark&quot;</b> - Sample large button with image
          </h5>
          <div className="mb-5">
            <Button
              variant="dark"
              size="lg"
              padding="0.4em 1.25em"
              href="https://discord.gg/RXySZQE"
            >
              <Image
                src="/images/discord-logo-white.svg"
                alt="Join our Discord"
                width={147}
                height={40}
                priority
              />
            </Button>
          </div>

          {/* Sample Heading component */}
          <div className="my-10">
            <HeadingBBAStyle>Follow us on Instagram</HeadingBBAStyle>
            <HeadingBBAStyle
              className="text-[2.5rem] font-bold text-sky-500"
              inverted={true}
            >
              @rrcbba
            </HeadingBBAStyle>
          </div>
        </div>{' '}
      </main>
      <FooterNavigation />
    </>
  );
}
