import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

// Components
import TopNavigation from '@/components/TopNavigation';
import FooterNavigation from '@/components/FooterNavigation';
import Button from '@/components/Button';
import HeadingBBAStyle from '@/components/HeadingBBAStyle';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavigation />
      <main>
        {/* Placeholder element */}
        <div className="container mx-auto" style={{ height: '600px' }}>
          {/* Sample buttons */}
          <div className="mb-5">
            <Button
              bgColor="bg-dark-button"
              padding="py-2 px-7"
              href="https://discord.gg/RXySZQE"
            >
              <Image
                src="/images/discord-logo-white.svg"
                alt="Join our Discord"
                width={147}
                height={40}
                priority
              />
            </Button>
          </div>
          <div className="mb-5">
            <Button href="#">Learn More</Button>
          </div>
          {/* Sample Heading component */}
          <HeadingBBAStyle>Follow us on Instagram</HeadingBBAStyle>
          <HeadingBBAStyle
            className="text-[2.5rem] font-bold text-sky-500"
            inverted={true}
          >
            @rrcbba
          </HeadingBBAStyle>
        </div>{' '}
      </main>
      <FooterNavigation />
    </>
  );
}
